name: car_rental_app
description: A professional car rental booking system

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Backend & data
  supabase_flutter: ^2.0.0
  google_maps_flutter: ^2.5.0

  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  uuid: ^4.2.0

  # Utilities
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
 

  # UI & visuals
  fl_chart: ^1.1.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0

  # State management
  provider: ^6.1.1
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
